language: go
sudo: false
go:
- 1.7
- 1.8
- 1.9
- '1.10'
- 1.11.x
- master

install:
- go get github.com/pkg/errors
- go get golang.org/x/lint/golint

script:
- golint ./...
- go test -v -race -coverprofile=coverage.txt -covermode=atomic

after_success:
- bash <(curl -s https://codecov.io/bash)
